default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backbone_development
  username: ikotsiuba
  password: postgres
  host: localhost
  #port: 5432

test:
  <<: *default
  database: backbone_test

production:
  <<: *default
  database: backbone_production
  username: backbone
  password: <%= ENV['BACKBONE_DATABASE_PASSWORD'] %>
